<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="58" started-at="2020-05-22T04:11:21Z" finished-at="2020-05-22T04:11:21Z">
    <groups>
    </groups>
    <test name="SeleniumWebDriverJava" duration-ms="58" started-at="2020-05-22T04:11:21Z" finished-at="2020-05-22T04:11:21Z">
      <class name="ejercicios.TestEmployeeDetails">
        <test-method status="FAIL" signature="testCalculador()[pri:0, instance:ejercicios.TestEmployeeDetails@2aafb23c]" name="testCalculador" duration-ms="17" started-at="2020-05-21T23:11:21Z" finished-at="2020-05-21T23:11:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[500 expected [96000.0] but found [500.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 500 expected [96000.0] but found [500.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEquals(Assert.java:225)
	at ejercicios.TestEmployeeDetails.testCalculador(TestEmployeeDetails.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculador -->
        <test-method status="PASS" signature="testCalculador2()[pri:0, instance:ejercicios.TestEmployeeDetails@2aafb23c]" name="testCalculador2" duration-ms="0" started-at="2020-05-21T23:11:21Z" finished-at="2020-05-21T23:11:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculador2 -->
      </class> <!-- ejercicios.TestEmployeeDetails -->
    </test> <!-- SeleniumWebDriverJava -->
  </suite> <!-- Default Suite -->
</testng-results>
